- Xero.Api/Core/Model/Invoice.cs
Added the missing element for SentToContact
> Added SentToContact in Invoices

- Xero.Api/Core/Model/TrackingCategory.cs
Added "Option" to "TrackingCategory" as JournalLine / TrackingCategory / Option does not exist
(As an aside, I expect JournalLines would actually have TrackingOptions rather than TrackingCategories)
Cheers!
D.
> Added "Option" to "TrackingCategory" as JournalLine / TrackingCategory / Option does not exist

- Xero.Api.Example.MVC/Xero.Api.Example.MVC.csproj
> Changes output path to bin rather than bin\release

- CoreTests/Integration/BankTransactions/Find.cs
- Xero.Api/Core/Endpoints/BankTransactionsEndpoint.cs
The endpoint will not page by default yet as this would be a breaking change
> Add paging to bank transactions. 

- CoreTests/Integration/Files/Files/AddFileTest.cs
- CoreTests/Integration/Files/Inbox/InboxTest.cs
> Updates Files tests to have file extension

- CoreTests/Integration/ManualJournals/Find.cs
- Xero.Api/Core/Endpoints/ManualJournalsEndpoint.cs
Added Paging for Manual Journals Endpoint
> Added Paging for Manual Journals

- Xero.Api.Example.MVC/Helpers/XeroApiHelper.cs
The partnerApplicationSettings should use partnerConsumer instead of publicConsumer
@philals
> Correct the partnerApplicationSettings

- CoreTests/Integration/Invoices/Create.cs
- Xero.Api/Core/Model/LineItem.cs
> Adds LineItemId to LineItems.

- CoreTests/Integration/Reports/Find.cs
NO FUNCTIONAL CHANGE
@MJMortimer
> Adds find examples for two reports

- CoreTests/Integration/Payments/Create.cs
- CoreTests/Integration/Payments/PaymentsTest.cs
- Xero.Api/Core/Model/Payment.cs
Added Prepayment and Overpayment properties to allow for pre/overpayment
refunds
> Added Prepayment and Overpayment

- Xero.Api/Core/Endpoints/ReportsEndpoint.cs
Added in second tracking ID and option parameters to allow pull requests using both tracking categories
> Update ProfitAndLoss parameters

- Xero.Api/Core/Model/Organisation.cs
@philals, quick addition of something that was missed
> Add missing EndOfYearLockDate to organisation

- Xero.Api/Core/Model/Status/TaxRateStatus.cs
@philals, ARCHIVED tax rate status was missing
> Added missing ARCHIVED tax rate status

- Xero.Api/Core/Model/Line.cs
> Added missing description to Line, used by Journals and ManualJournals

- Xero.Api/Core/Model/Account.cs
- Xero.Api/Core/Model/Types/BankAccountType.cs
- Xero.Api/Xero.Api.csproj
Missing property and enum included
Apologies for the whitespace changes in the commit. If I get chance I'll see if I can remove it.
> Add BankAccountType to Account

- Xero.Api/Core/Model/Journal.cs
- Xero.Api/Core/Model/Types/SourceType.cs
- Xero.Api/Xero.Api.csproj
Again, apologies for the whitespace differences
> Add SourceType and SourceId to Journal

- CoreTests/Integration/Overpayments/Find.cs
- CoreTests/Integration/Prepayments/Find.cs
- Xero.Api/Serialization/DefaultMapper.cs
> Add both ProverpaymentTypes to the Default serialization mapper as they were missing

- Xero.Api/Core/Model/Invoice.cs
> Add TotalDiscount to Invoice.cs

- Xero.Api/Serialization/DefaultMapper.cs
Updated DefaultMapper.cs to handle nullable types
> Nullable Type Deserializer Fix

- Xero.Api/Core/Model/ItemTrackingCategory.cs
Added TrackingOptionID to the LineItems Tracking Category object
> Added TrackingOptionID

- README.md
> Adds Appveyor build badge

- CoreTests/CoreTests.csproj
- CoreTests/Integration/PurchaseOrders/Update.cs
- Xero.Api/Core/Endpoints/PurchaseOrdersEndpoint.cs
- Xero.Api/Core/Model/PurchaseOrder.cs
> POST Purchase Orders

- CoreTests/Unit/SummarizeErrors.cs
> Adds unit tests for Api.SummarizeErrors(false/true);

- Xero.Api/Core/Endpoints/BankTransfersEndpoint.cs
- Xero.Api/Core/IXeroCoreApi.cs
- Xero.Api/Core/XeroCoreApi.cs
Also restructured it to be more maintainable. 
Updated BankTransfers endpoint to be create only as Xero doesn't update them yet.
@philals
> Added the new endpoints to the api core interface. 

- Xero.Api/Core/Endpoints/SetupEndpoint.cs
- Xero.Api/Core/IXeroCoreApi.cs
- Xero.Api/Core/XeroCoreApi.cs
Continuing our work to make the API more testable
> Create a SetupEndpoint interface (as it's not like the others)

- Xero.Api/Payroll/Australia/Model/Employee.cs
- Xero.Api/Payroll/Australia/Model/LeaveBalance.cs
This PR requires testing, I'm unable to test locally.
Code was provided by a dev from our ecosystem.
Documentation regarding leave balances is here: http://developer.xero.com/documentation/payroll-api/leavebalances/
And here: http://developer.xero.com/documentation/payroll-api/employees/
> Added LeaveBalances to the AU Payroll (Employees)

- CoreTests/Integration/Pdf/Get.cs
- CoreTests/Integration/PurchaseOrders/Create.cs
- Xero.Api/Core/Model/Types/PdfEndpointType.cs
> Added the ability to get purchase orders as pdf

- CoreTests/CoreTests.csproj
- CoreTests/Integration/Invoices/OnlineInvoiceUrl.cs
- Xero.Api/Core/Endpoints/InvoicesEndpoint.cs
- Xero.Api/Core/Model/OnlineInvoice.cs
- Xero.Api/Core/Request/OnlineInvoicesRequest.cs
- Xero.Api/Core/Response/OnlineInvoicesResponse.cs
- Xero.Api/Xero.Api.csproj
> Added OnlineInvoiceUrl functionality

- Xero.Api/Infrastructure/Exceptions/BadRequestException.cs
- Xero.Api/Infrastructure/Exceptions/NotAvailableException.cs
- Xero.Api/Infrastructure/Exceptions/NotFoundException.cs
- Xero.Api/Infrastructure/Exceptions/RateExceededException.cs
- Xero.Api/Infrastructure/Exceptions/UnauthorizedException.cs
- Xero.Api/Infrastructure/Exceptions/ValidationException.cs
- Xero.Api/Infrastructure/Exceptions/XeroApiException.cs
Clone of #204 updated with master for merge
> Added paramaterless constructors to exceptions

- Xero.Api/Core/XeroCoreApi.cs
The Rate limiter wasn't being passed down the constructor line
> Rate limiter wasn't getting passed down

- Xero.Api/Common/IHasAttachment.cs
- Xero.Api/Core/Model/Account.cs
- Xero.Api/Core/Model/BankTransaction.cs
- Xero.Api/Core/Model/BankTransfer.cs
- Xero.Api/Core/Model/Contact.cs
- Xero.Api/Core/Model/CreditNote.cs
- Xero.Api/Core/Model/Invoice.cs
- Xero.Api/Core/Model/ManualJournal.cs
- Xero.Api/Core/Model/Overpayment.cs
- Xero.Api/Core/Model/Prepayment.cs
- Xero.Api/Core/Model/PurchaseOrder.cs
- Xero.Api/Core/Model/Receipt.cs
- Xero.Api/Core/Model/RepeatingInvoice.cs
- Xero.Api/Xero.Api.csproj
A small non-breaking change here. We'd like to be able to treat any entity with attachments as the same type so an interface seems appropriate for it.
> Add an interface to indicate whether an entity can have attachments

- README.md
Updated the code sections to leverage syntax highlighting for C# and XML
> Updated README.md with Code Syntax

- CoreTests/README.md
- PayrollTests.AU/README.md
- PayrollTests.US/README.md
- Xero.Api.Example.Counts/README.md
- Xero.Api.Example.Creation/README.md
- Xero.Api.Example.MVC/README.md
- Xero.Api/README.md
Formatted README's with spaces so GitHub markdown rendering will show
the section headers
> Update README.md with Section Formatting

- CoreTests/Integration/Invoices/Find.cs
- CoreTests/Integration/Invoices/InvoicesTest.cs
- Xero.Api/Core/Endpoints/InvoicesEndpoint.cs
- Xero.Api/Core/Model/EnumExtensions.cs
- Xero.Api/Xero.Api.csproj
Adds more options to filter invoices by one or more comma separated lists. Adds ContactIds, InvoiceNumbers, Statuses
> Added extra query parameter filters to invoices endpoint

- Xero.Api/Core/Endpoints/CreditNotesEndpoint.cs
Pretty self explanatory now that the API supports this
> Add paging to Credit Notes

- Xero.Api/Core/Endpoints/FilesEndpoint.cs
- Xero.Api/Core/Model/Types/ObjectGroupType.cs
- Xero.Api/Core/Model/Types/ObjectType.cs
Also sets 1 to be default values for ObjectGroupType and ObjectType enums
> Enable Paging for Files Endpoint

- Xero.Api/Core/Endpoints/AllocationEndpoint.cs
- Xero.Api/Core/Model/Types/ObjectType.cs
- Xero.Api/Infrastructure/Exceptions/RateExceededException.cs
- Xero.Api/Infrastructure/Http/Response.cs
- Xero.Api/Infrastructure/Http/XeroHttpClient.cs
Had this value returned to us through the API that was missing in the list
> Add Business as an ObjectType

- Xero.Api/Core/Model/TaxComponent.cs
Add support for non-recoverable tax components that have recently been added to the API: https://developer.xero.com/documentation/api/tax-rates
> Add IsNonRecoverable column to TaxComponent.

- Xero.Api/Core/Endpoints/InvoicesEndpoint.cs
FYI: You will not be able to use this functionality if you're not in the beta
> Email invoice functionality

- Xero.Api/Core/Endpoints/ContactsEndpoint.cs
- Xero.Api/Core/Endpoints/OrganisationEndpoint.cs
- Xero.Api/Core/IXeroCoreApi.cs
- Xero.Api/Core/Model/ContactCisSetting.cs
- Xero.Api/Core/Model/CreditNote.cs
- Xero.Api/Core/Model/Invoice.cs
- Xero.Api/Core/Model/OrganisationCisSetting.cs
- Xero.Api/Core/Response/ContactCisSettingsResponse.cs
- Xero.Api/Core/Response/OrganisationCisSettingsResponse.cs
- Xero.Api/Core/XeroCoreApi.cs
- Xero.Api/Xero.Api.csproj
Also includes CISDeductions for invoices and credit notes
> Cis settings for contacts and orgs

- Xero.Api/Serialization/DefaultMapper.cs
> Allow nullable LineAmountTypes to be serialized correctly. Includes support for nullable ManualJournalStatus

- Xero.Api/Core/Model/Payment.cs
To be able to bring back batch payment id when query invoices.
> Add batch payment id to invoice class

- Xero.Api/Core/Endpoints/JournalsEndpoint.cs
Copy of #344 with correct naming
> Add paymentsOnly param to JournalsEndpoint

- Xero.Api.Example.Applications/Public/PublicMvcAuthenticator.cs
Add organisation shortcode so accesstoken is compatible with SQLiteTokenStore
> Add organisationShortCode to access token

- Xero.Api/Core/Model/Organisation.cs
> Add EmployerIdentificationNumber to organisation model

- Xero.Api/Core/Model/Status/BankTransactionStatus.cs
> Issue-401: Added missing BankTransactionStatus 'VOIDED'

- Xero.Api/Core/Model/Types/PhoneType.cs
> Issue-403: Added missing OFFICE enum value for phone type

- Xero.Api/Core/Model/Overpayment.cs
- Xero.Api/Core/Model/Prepayment.cs
> Add field AppliedAmount to Overpayment and Prepayment

- Xero.Api/Core/Model/LineItem.cs
Added a DiscountAmount into the LineItem class
> Added DiscountAmount
