Xero.Api/Payroll/Australia/Model/SuperannuationLine.cs

Riley has confirmed to me that these properties are a bug in the wrapper and should be strings as both string characters are valid in an AccountCode. Both the UI and the API will accept strings.

Changed SuperannuationLine Model AccountCode properties from int to string

---

Xero.Api/Core/File/BinaryFile.cs
Xero.Api/Core/Model/Invoice.cs
Xero.Api/Infrastructure/ThirdParty/Dust/Core/SignatureBaseStringParts/Parameters/RequestParameters.cs

This fix resolves an issue whereby finding contacts using the where clause "TaxNumber != NULL AND TaxNumber.Replace(" ","") == "1234"", and other various object types, throws a Failed to validate signature exception due to the query string being incorrectly split into multiple request parameters.

Fix for failed to validate signature exception when where clause contains a comma (,)

---

Xero.Api/Core/Model/Status/PaymentStatus.cs

The PaymentStatus enum was missing the DELETED member.

Add missing Payment Status = DELETED

---

Xero.Api/Common/IHasId.cs
Xero.Api/Core/Model/Account.cs
Xero.Api/Core/Model/Attachment.cs
Xero.Api/Core/Model/BankTransaction.cs
Xero.Api/Core/Model/BankTransfer.cs
Xero.Api/Core/Model/Contact.cs
Xero.Api/Core/Model/ContactGroup.cs
Xero.Api/Core/Model/CreditNote.cs
Xero.Api/Core/Model/Employee.cs
Xero.Api/Core/Model/ExpenseClaim.cs
Xero.Api/Core/Model/Invoice.cs
Xero.Api/Core/Model/Item.cs
Xero.Api/Core/Model/ItemTrackingCategory.cs
Xero.Api/Core/Model/Journal.cs
Xero.Api/Core/Model/Line.cs
Xero.Api/Core/Model/ManualJournal.cs
Xero.Api/Core/Model/Option.cs
Xero.Api/Core/Model/Payment.cs
Xero.Api/Core/Model/Receipt.cs
Xero.Api/Core/Model/RepeatingInvoice.cs
Xero.Api/Core/Model/TrackingCategory.cs
Xero.Api/Core/Model/User.cs
Xero.Api/Xero.Api.csproj

Added an IHasId interface to all core models that have an Id property. Amongst other uses this can be used in generic constraints to allow generics to access the Id property. 
I did not apply this to the BrandingTheme or ContactPerson models as I noticed that their Id properties are not named Id (instead they are BrandingThemeId and ContactPersonId). As such I didn't know whether they should be changed to Id to be consistent with the other models, or whether an new Id property should be added that redirects to the existing one.

Added IHasId interface to core models

---

Xero.Api/Core/Model/Types/PaymentType.cs

AR and AP credit payments were defaulting to PaymentType.AccountsPayable due to missing enum fields.

Enum fields added for missing payment types

---

Xero.Api/Infrastructure/Http/XeroHttpClient.cs

Setting the 'modified since' date once using the XeroReadEndpoint.ModifiedSince call retains the date/time value for future calls that don't specify a 'modified since' time.
Removed the not-null check as null is a valid value.

ModifiedSince incorrectly retained between calls?

---

Xero.Api/Core/Model/Overpayment.cs
Xero.Api/Core/Model/Status/OverpaymentStatus.cs

Issue : OverpaymentStatus enum values do not reflect the API
- Align the OverpaymentStatus enum with the API response definitions; DELETED doesn't exist as a status code as documented: http://developer.xero.com/documentation/api/types/#OverpaymentStatuses.  
- Added missing PAID status.

OverpaymentStatus Fixes

---

Xero.Api/Core/Model/CreditNote.cs
Xero.Api/Core/Model/Overpayment.cs

Reflect the correct container types (CreditNote / Overpayment).

Fix up generic list declarations for items with Allocations

---

Xero.Api/Infrastructure/Http/Response.cs

Gives the ability to read the body of a Response more than once. Useful for when inspecting the Response when debugging

Store the body of the Response after reading the stream.

---

CoreTests/Integration/Attachments/Attachments.cs
CoreTests/Integration/General/Errors.cs
CoreTests/Integration/Invoices/Create.cs
CoreTests/Integration/Invoices/InvoicesTest.cs
CoreTests/Integration/Invoices/SummarizeErrors.cs
CoreTests/Integration/Payments/PaymentsTest.cs
CoreTests/Integration/TrackingCategories/TrackingCategoriesTest.cs
Xero.Api.Example.Creation/ApiDataCreation.cs
Xero.Api/Core/Model/Invoice.cs

Gives consistency accross models that use line items. Change all references of Items in tests etc to LineItems from Items.

Add LineItems to Invoice.cs and make Items obselete. 

---

Xero.Api/Infrastructure/Http/HttpClient.cs

If there is no response throw the exception back up for the client to catch and decide how to handle it.

Add null checks before creating responses from WebException responses.

---

CoreTests/CoreTests.csproj
CoreTests/Integration/ContactGroups/Find.cs

No functional changes. Just a example on how to use ContactGroups.Find() as per ticket request.
@MJMortimer

Adds tests around ContactGroups.Find as examples on how to use .Find()

---

Xero.Api/Core/Model/Invoice.cs

The invoices API endpoint return an Invoice object that includes a Payments property, but this property was missing from the SDK.  The change in this PR will add this missing property.

Added Invoice.Payments

---

Xero.Api/Infrastructure/Exceptions/UnauthorizedException.cs
Xero.Api/Infrastructure/OAuth/OAuthException.cs

Throwing internal exceptions that aren't being caught and handled, or
throwing other exceptions is a problem
https://msdn.microsoft.com/en-us/library/bb264484.aspx
Doesn't appear that there are any other usages of these exceptions other than just the throw...

Change access modifiers for UnauthorizedException and OAuthException

---

Xero.Api/Core/Model/Types/SystemAccountType.cs

SystemAccountType.cs incorrectly set to Tax rather than GST for 'GST /
VAT' and 'GST On Imports' as per documentation:
http://developer.xero.com/documentation/api/types/#SystemAccounts

SystemAccountType enum value correction

---

CoreTests/CoreTests.csproj
CoreTests/Unit/RateLimiterTest.cs
Xero.Api/Common/XeroApi.cs
Xero.Api/Core/XeroCoreApi.cs
Xero.Api/Infrastructure/Http/HttpClient.cs
Xero.Api/Infrastructure/Http/XeroHttpClient.cs
Xero.Api/Infrastructure/RateLimiter/IRateLimiter.cs
Xero.Api/Infrastructure/RateLimiter/RateLimiter.cs
Xero.Api/Payroll/AmericanPayroll.cs
Xero.Api/Payroll/AustralianPayroll.cs
Xero.Api/Payroll/Common/PayrollApi.cs
Xero.Api/Xero.Api.csproj

The API enforces that no more than 60 requests can be made over a 60 second period. It's useful to have the option for the API to handle that if you are making lots of requests, as the delay can be more convenient than the exception and retrying.
Note that this would also work for the daily limit, but would probably need refactoring so that you'd know to not block for many hours.
Happy to make any modifications based on feedback, but this is a feature we'd really like to see in the core wrapper.

Rate limiter

---

Xero.Api/Core/Model/ExpenseClaim.cs

As suggested by Xero Developer support team, I have added Payments property to ExpenseClaims.
Tested locally and it worked fine.
Please merge the change into your master branch.

Add Payments property to ExpenseClaim

---

Xero.Api/Core/Model/CreditNote.cs
Xero.Api/Core/Model/Overpayment.cs
Xero.Api/Core/Model/Prepayment.cs

When cash refunds are made to credit notes, the API returns them as Payments in the restful interface. I have added the property to credit notes and they are loaded in automatically when they are present.

Add payments to credit notes

---

README.md

Corrected Readme Typo which was redirecting to dead link `http://deverloper.xero.com` instead of `http://developer.xero.com`

Corrected Readme Typo which was redirecting to dead link

---

Xero.Api/Core/Model/Payment.cs

Last year, BankAmount was added to Payments endpoint according to the release note below.
http://developer.xero.com/documentation/api/v2-release-notes/#2.130
I would like to use this but unfortunately in Xero-Net, we do not have such property at the moment.
I suppose it was just missed updating Xero-Net at the time of the release above.
I added it and tested on my local environment. It worked fine.
Please accept my pull request.

Add BankAmount property to Payment

---

CoreTests/CoreTests.csproj
CoreTests/Unit/ExceptionTests.cs
Xero.Api/Infrastructure/Exceptions/ValidationException.cs

I hit a condition today where the API was returning an ApiException that had multiple DataContractBase instances with ValidationErrors.  One of the DataContractBase instances had a 'null' ValidationErrors collection (for some reason, possibly due to a large response?), generating an unhandled exception in the ApiException constructor.
This is a test + fix to ensure the condition is guarded.

Check for null ValidationErrors on ApiException parsing

---

Xero.Api/Core/Model/CreditNote.cs
Xero.Api/Core/Model/Receipt.cs

While we're on the subject of breaking changes, these are to make some of the objects more consistent with each other. For example, some of the fields are nullable on Invoice, but not on CreditNote etc

Make SubTotal, Total and TotalTax consistent types

---

PayrollTests.AU/Integration/Employees/Create.cs
PayrollTests.AU/Integration/Employees/EmployeesTest.cs
PayrollTests.AU/Integration/SuperFunds/Create.cs
PayrollTests.AU/Integration/SuperFunds/Update.cs
Xero.Api/Payroll/Australia/Model/BankAccount.cs
Xero.Api/Payroll/Australia/Model/SuperFund.cs
Xero.Api/Payroll/Australia/Model/SuperFundProduct.cs

There are several banks in Australia and New Zealand which have a 0 at the
front of their BSB numbers eg Commonwealth Bank. With the type as an
integer it drops the leading 0 which gives a validation error when sent to
the server as the BSB is too short.
The first two digits of an ABN number is a checksum which can also contain
a zero.
You're not going to add a bank account to another bank account number and
divide it by their BSB and times it by their ABN.
Rule of thumb: If you not doing arithmetic with the numbers, store them as
a string.

Changed account number, BSB and ABN to type string.

---

Xero.Api/Core/IXeroCoreApi.cs
Xero.Api/Core/XeroCoreApi.cs

Rather than set this for each object type whenever we use it, we'd rather be able to set it once per instance of the endpoint we create

Allow SummariseErrors to be set at the API level for all entities

---

Xero.Api/Core/Model/LineItem.cs

The API expects LineItemID. This makes it so it will serialize correctly
@philals

Have LineItemId serialize out to LineItemID

---

CoreTests/CoreTests.csproj
CoreTests/packages.config

When a clean solution is opened in VS, no tests are being shown in the Test explorer.
I guess this works for you guys as you have nUnit VSIX (Resharper) installed on your machines. However, there is a way howto enable nUnit tests without a need of installing anything on the dev machine - Install `NUnitTestAdapter` NuGet package to any of your projects in solution.
I think this is a more convenient way for a new developer setting up solution.

nUnit tests not shown in Test Explorer

---

Xero.Api/Core/Model/Line.cs

The wrong tracking objects are being used for Manual Journals and Journals which means that they can't be saved or loaded through the API

Use correct tracking object on Line

---

Xero.Api/Infrastructure/Http/HttpClient.cs

Our understanding is that the API has a timeout of 200 seconds. The [default](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout) is 100 seconds. We'd like this to be set to a larger number (300 seconds) so that we can be sure that no processing is still ongoing (as we've previously had issues where a request has "timed out" but the results have actually been saved in the API

Set timeout to 5 minutes to cater for slow requests

---

Xero.Api.Example.Applications/Public/PublicMvcAuthenticator.cs

Do not return expired access tokens in the MVC example authenticators

---

Xero.Api/Core/Model/Types/BankAccountType.cs

Hi, it looks like there is a missing bank account type in the mapping. I get an exception very often when getting a bill from Xero. Despite of the fact this exception is being swallowed somewhere I think the enum should be mapped correctly.

Added missing value None to the BankAccountType enum

---

nuget.nuspec

Orginally NewtonSoft.Json (capital S).
This caused a duplicate key exception during startup of referencing application if another library was used with a dependency on Newtonsoft.Json.

Updated Nuget dependency on Newtonsoft.Json

---

Xero.Api/Payroll/Australia/Model/SuperannuationLine.cs

It retrieves ContributionType=null, works fine for other types. making it non nullable fixes it.
used
api.Payslips.Find(payslipId);

Payslips api not reading ContributionType If ContributionType =SuperannuationGuaranteeCharge

---

Xero.Api/Payroll/America/Endpoints/PayItemsEndpoint.cs
Xero.Api/Payroll/America/Model/BankAccount.cs
Xero.Api/Payroll/America/Model/SalaryAndWage.cs
Xero.Api/Payroll/America/Request/PayItemsRequest.cs
Xero.Api/Payroll/America/Response/PayItemsResponse.cs
Xero.Api/Payroll/AmericanPayroll.cs
Xero.Api/Payroll/Australia/Model/EarningsRate.cs
Xero.Api/Payroll/Australia/Model/PayItems.cs
Xero.Api/Xero.Api.csproj

Changed from Int32 to String for both AccountNumber and RoutingNumber.  And Int32 is not large enough to hold most American bank account numbers and the XERO API is expecting a string.

Changed model types for AmericanPayroll

---

PayrollTests.AU/Integration/PayItems/Find.cs
Xero.Api/Payroll/Australia/Model/EarningsRate.cs
Xero.Api/Payroll/Australia/Model/PayItems.cs

*reverted changes from f7213975980561ad2032b6ea24c0ce0b1bdf01f to get PayItems.EarningRates working again
* added EarningRates.IsReportableAsW1 as it was missing from the SDK

* PayItems.EarningRates working again and added EarningRates.IsReportableAsW1

---

CoreTests/Integration/Contacts/Find.cs
Xero.Api/Core/Endpoints/ContactsEndpoint.cs

Similar to how InvoicesEndpoint has an Ids method to find multiple
Invoices at the same time, this method is for retrieving multiple
contacts at the same time which helps with batching requests and not
hitting the API request limit as quickly when fetching a lot of data, and I've added a unit test for completeness.

Contacts Endpoint - Method to fetch multiple contacts at the same time.

---

Xero.Api/Infrastructure/RateLimiter/RateLimiter.cs

I changed the `while` to an `if` because the previous implementation would always return `false` the second time that condition was checked. The queue is dequeued with each enqueue and all the properties involved are private, so it's safe to assume the condition only needs to be checked once. Note, this is not thread safe, but RateLimiter already is not thread safe (https://github.com/XeroAPI/Xero-Net/issues/248).

While condition is always true the second time

---

CoreTests/Integration/Organisation/Find.cs
Xero.Api/Common/XeroReadEndpoint.cs
Xero.Api/Core/Model/Organisation.cs
Xero.Api/Core/Model/Types/SalesTaxBasisType.cs

To fix issue 
https://github.com/XeroAPI/Xero-Net/issues/377
SalesTaxBasis wasn't populated because of the class member name is "SalesTaxBasisType", by mapping it to SalesTaxBasis will fix the problem.
Also, for US org, it seems "ACCRUAL" is showing as "ACCRUALS", so I've added that to enum SalesTaxBasisType.. 😭 
ping @MJMortimer

Change Organisation map SalesTaxBasis to SalesTaxBasisType

---

CoreTests/CoreTests.csproj
CoreTests/Integration/BatchPayment/BatchPaymentsTest.cs
CoreTests/Integration/BatchPayment/Create.cs
Xero.Api/Core/Model/BatchPayment.cs

The payment date of the batch payment should be passed as a string in the format yyyy-MM-dd according to the Xero API docs page however as it was being parsed as a date, it was subject to the timezone difference between the API user and Xero, so if you parsed a date object without a timepart, you could end up with yesterday's date being set for the payment date.
See https://developer.xero.com/documentation/api/batch-payments#PUT 
Example request and response where using the current version published on nuget, sets the date incorrectly.
[batch payment request.xml.txt](https://github.com/XeroAPI/Xero-Net/files/3604926/batch.payment.request.xml.txt)
[response.json.txt](https://github.com/XeroAPI/Xero-Net/files/3604925/response.json.txt)

Changes to BatchPayment to avoid timezone Issue

---

Xero.Api/Infrastructure/Http/Response.cs

Attempt to resolve #383 .
Added inner.close to Xero.Api.Infrastructure.Http: internal Response(HttpWebResponse inner)
Closing the HttpWebResponse seems to resolve the issue that after sending ~2 emails, the ServicePointManager uses up its two connections (default limit) and any further connections time out.

383 email invoice timeout
